export interface Product {
  id: number;
  name: string;
  image: string;
  category: string;
  rating: number;
  reviewCount: number;
  description?: string;
}

export const categories = [
  "All",
  "Apparel and accessories",
  "Bags and travel",
  "Eating and drinking",
  "Eco friendly",
  "Gift Sets",
  "Office and stationary",
  "Premiums and tools",
  "Sports and recreation",
  "Technology and accessories",
];

export const products: Product[] = [
  {
    id: 1,
    name: "AGENDA PEN",
    image: "/api/placeholder/300/300",
    category: "Office and stationary",
    rating: 5,
    reviewCount: 0,
    description:
      "Premium metallic pens in various colors with silver clips and tips",
  },
  {
    id: 2,
    name: "AGENDA",
    image: "/api/placeholder/300/300",
    category: "Office and stationary",
    rating: 5,
    reviewCount: 0,
    description: "Professional notebooks and agendas in multiple colors",
  },
  {
    id: 3,
    name: "COZY NOTE",
    image: "/api/placeholder/300/300",
    category: "Office and stationary",
    rating: 5,
    reviewCount: 0,
    description: "Soft-textured notebooks with elastic band closures",
  },
  {
    id: 4,
    name: "RPET B5",
    image: "/api/placeholder/300/300",
    category: "Eco friendly",
    rating: 5,
    reviewCount: 0,
    description: "Eco-friendly notebook made from recycled PET materials",
  },
  {
    id: 5,
    name: "TRAIL - Santhome® Reversible",
    image: "/api/placeholder/300/300",
    category: "Apparel and accessories",
    rating: 5,
    reviewCount: 0,
    description: "Reversible bucket hat in black and white with logo patch",
  },
  {
    id: 6,
    name: "BENDI",
    image: "/api/placeholder/300/300",
    category: "Technology and accessories",
    rating: 5,
    reviewCount: 0,
    description: "Sleek wireless headphones with minimalist design",
  },
  {
    id: 7,
    name: "Premium Backpack",
    image: "/api/placeholder/300/300",
    category: "Bags and travel",
    rating: 4.8,
    reviewCount: 12,
    description: "Durable travel backpack with multiple compartments",
  },
  {
    id: 8,
    name: "Stainless Steel Bottle",
    image: "/api/placeholder/300/300",
    category: "Eating and drinking",
    rating: 4.9,
    reviewCount: 8,
    description: "Insulated stainless steel water bottle",
  },
  {
    id: 9,
    name: "Corporate Gift Set",
    image: "/api/placeholder/300/300",
    category: "Gift Sets",
    rating: 4.7,
    reviewCount: 15,
    description: "Premium corporate gift set with multiple items",
  },
  {
    id: 10,
    name: "Multi-Tool Kit",
    image: "/api/placeholder/300/300",
    category: "Premiums and tools",
    rating: 4.6,
    reviewCount: 6,
    description: "Compact multi-tool kit for professionals",
  },
  {
    id: 11,
    name: "Yoga Mat",
    image: "/api/placeholder/300/300",
    category: "Sports and recreation",
    rating: 4.8,
    reviewCount: 20,
    description: "Non-slip yoga mat with carrying strap",
  },
  {
    id: 12,
    name: "Wireless Charger",
    image: "/api/placeholder/300/300",
    category: "Technology and accessories",
    rating: 4.5,
    reviewCount: 9,
    description: "Fast wireless charging pad for smartphones",
  },
  {
    id: 13,
    name: "Leather Wallet",
    image: "/api/placeholder/300/300",
    category: "Apparel and accessories",
    rating: 4.9,
    reviewCount: 18,
    description: "Genuine leather wallet with RFID protection",
  },
  {
    id: 14,
    name: "Travel Organizer",
    image: "/api/placeholder/300/300",
    category: "Bags and travel",
    rating: 4.7,
    reviewCount: 11,
    description: "Compact travel organizer for toiletries and accessories",
  },
  {
    id: 15,
    name: "Coffee Mug Set",
    image: "/api/placeholder/300/300",
    category: "Eating and drinking",
    rating: 4.8,
    reviewCount: 14,
    description: "Set of 4 ceramic coffee mugs with company logo",
  },
  {
    id: 16,
    name: "Bamboo Cutlery Set",
    image: "/api/placeholder/300/300",
    category: "Eco friendly",
    rating: 4.6,
    reviewCount: 7,
    description: "Sustainable bamboo cutlery set with carrying case",
  },
  {
    id: 17,
    name: "Executive Gift Box",
    image: "/api/placeholder/300/300",
    category: "Gift Sets",
    rating: 4.9,
    reviewCount: 22,
    description: "Luxury executive gift box with premium items",
  },
  {
    id: 18,
    name: "Desk Organizer",
    image: "/api/placeholder/300/300",
    category: "Office and stationary",
    rating: 4.5,
    reviewCount: 13,
    description: "Modern desk organizer with multiple compartments",
  },
];
